apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi  # Must match the capacity specified in the PV
  storageClassName: microk8s-hostpath  # Modify based on your storage class